### ISSUE TITLE
asasatels task fails when attempting to unzip '/root/better-atel/atels.json.gz'

### ISSUE THREAD

**Issue by Zeklandia** [astrocatalogs/supernovae#143]
This occured while using `astrocats` to import `supernovae`.

```
 - - - Task: 'asasatels'
Traceback (most recent call last):
  File ".../anaconda3/envs/astro3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File ".../anaconda3/envs/astro3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../astrocats/astrocats/__main__.py", line 6, in <module>
    main.main()
  File ".../astrocats/astrocats/main.py", line 68, in main
    mod.main.main(args, sub_clargs, log)
  File ".../astrocats/astrocats/supernovae/main.py", line 23, in main
    args_handler.run_subcommand(args, catalog)
  File ".../astrocats/astrocats/catalog/argshandler.py", line 21, in run_subcommand
    catalog.import_data()
  File "...astrocats/astrocats/catalog/catalog.py", line 271, in import_data
    getattr(mod, func_name)(self)
  File "...astrocats/astrocats/supernovae/tasks/asassn.py", line 108, in do_asas_atels
    with gzip.open('/root/better-atel/atels.json.gz', 'rb') as f:
  File ".../anaconda3/envs/astro3/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File ".../anaconda3/envs/astro3/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: '/root/better-atel/atels.json.gz'
```

**Comment by guillochon** [comment]
Hi @Zeklandia, this actually runs off of a sibling process that is not available in the main supernova repo just yet. I've pushed a change that will skip this task: https://github.com/astrocatalogs/supernovae/commit/a2c543d76617ab3812568c8de06627156b88dd84.
